---
csr1:
  bgp:
    asn: 65511
    rid: 1.1.1.1
    neighbors:
      - ipaddr: 10.10.12.2
        remote_asn: 65512
      - ipaddr: 10.10.13.3
        remote_asn: 65513
  interfaces:
    GigabitEthernet4:
      ipaddr: 10.10.12.1
      mask: 255.255.255.252
      description: Link to csr2
      state: up
    GigabitEthernet2:
      ipaddr: 10.10.13.1
      mask: 255.255.255.248
      description: Link to csr3
      state: up
csr2:
  bgp:
    asn: 65512
    rid: 2.2.2.2
    neighbors:
      - ipaddr: 10.10.12.1
        remote_asn: 65511
      - ipaddr: 10.10.23.3
        remote_asn: 65513
  interfaces:
    GigabitEthernet3:
      ipaddr: 10.10.23.2
      mask: 255.255.255.248
      description: Link to csr3
      state: up
    GigabitEthernet4:
      ipaddr: 10.10.12.2
      mask: 255.255.255.252
      description: Link to csr1
      state: up
csr3:
  bgp:
    asn: 65513
    rid: 3.3.3.3
    neighbors:
      - ipaddr: 10.10.13.1
        remote_asn: 65511
      - ipaddr: 10.10.23.2
        remote_asn: 65512
  interfaces:
    GigabitEthernet2:
      ipaddr: 10.10.13.3
      mask: 255.255.255.248
      description: Link to csr1
      state: up
    GigabitEthernet3:
      ipaddr: 10.10.23.3
      mask: 255.255.255.248
      description: Link to csr2
      state: up


